# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_result_testvalue_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='versionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Version'),
        ),
        migrations.AlterField(
            model_name='testvalue',
            name='versionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Version'),
        ),
    ]
