# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20170819_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='networkType',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='testvalue',
            name='networkType',
            field=models.CharField(max_length=10),
        ),
    ]
