# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20170819_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='versionID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testvalue',
            name='versionID',
            field=models.IntegerField(),
        ),
    ]
