# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20170819_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='killtime',
            new_name='avgtime',
        ),
        migrations.RenameField(
            model_name='testvalue',
            old_name='killtime',
            new_name='avgtime',
        ),
        migrations.RemoveField(
            model_name='testvalue',
            name='mailcount',
        ),
    ]
